version: '3.8'

services:
  db:
#    restart: unless-stopped
    image: postgres:13
    container_name: tender-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tender-service
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M

  app:
#    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tender-service-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: tender-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 256M