// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка). 
 *
 * API version: 1.0
 */

package openapi




type CreateBidRequest struct {

	// Полное название предложения
	Name string `json:"name"`

	// Описание предложения
	Description string `json:"description"`

	Status BidStatus `json:"status"`

	// Уникальный идентификатор тендера, присвоенный сервером.
	TenderId string `json:"tenderId"`

	// Уникальный идентификатор организации, присвоенный сервером.
	OrganizationId string `json:"organizationId"`

	// Уникальный slug пользователя.
	CreatorUsername string `json:"creatorUsername"`
}

// AssertCreateBidRequestRequired checks if the required fields are not zero-ed
func AssertCreateBidRequestRequired(obj CreateBidRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"description": obj.Description,
		"status": obj.Status,
		"tenderId": obj.TenderId,
		"organizationId": obj.OrganizationId,
		"creatorUsername": obj.CreatorUsername,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateBidRequestConstraints checks if the values respects the defined constraints
func AssertCreateBidRequestConstraints(obj CreateBidRequest) error {
	return nil
}
