// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка). 
 *
 * API version: 1.0
 */

package openapi




type CreateTenderRequest struct {

	// Полное название тендера
	Name string `json:"name"`

	// Описание тендера
	Description string `json:"description"`

	ServiceType TenderServiceType `json:"serviceType"`

	Status TenderStatus `json:"status"`

	// Уникальный идентификатор организации, присвоенный сервером.
	OrganizationId string `json:"organizationId"`

	// Уникальный slug пользователя.
	CreatorUsername string `json:"creatorUsername"`
}

// AssertCreateTenderRequestRequired checks if the required fields are not zero-ed
func AssertCreateTenderRequestRequired(obj CreateTenderRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"description": obj.Description,
		"serviceType": obj.ServiceType,
		"status": obj.Status,
		"organizationId": obj.OrganizationId,
		"creatorUsername": obj.CreatorUsername,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateTenderRequestConstraints checks if the values respects the defined constraints
func AssertCreateTenderRequestConstraints(obj CreateTenderRequest) error {
	return nil
}
